project:
  type: website
  output-dir: docs

website:
  title: "Slides + webR"
  navbar:
    left:
      - text: "Demo"
        href: slides/demo.qmd
      - href: slides/demo2.qmd
        text: Demo 2
      - href: slides/statitik-1.qmd
        text: statistik 1
      - href: slides/data-fallacies.qmd
        text: data fallacies
      - href: slides/statistik-47.qmd
        text: side-by-side forsøg

format:
  # fælles HTML-indstillinger for live-sider
  live-html:
    theme: cosmo
