---
title: "Statistik"
subtitle: "Intro" 
format: revealjs
engine: knitr
filters:
  - webr
webr:
  packages: ["gt", "tidyverse"]
---
{{< include ../_extensions/r-wasm/live/_knitr.qmd >}}

## Formålet med statistik

”Statistics is the science of collecting, summarizing, presenting and interpreting data, and of using them to estimate the magnitude of associations and test hypotheses. It has a central role in medical investigations” Indledende afsnit i lærebogen ”Medical statistics””

:::{.notes}
Det vil sige at vi bruger statistik til at forstå, estimere og udlede 
information, baseret på data.
:::

## Målet med statistik

:::{.incremental}
* Deskriptiv statistik
  - Histogrammer
  - Gennemsnit, median
  - Spredning, percentiler, range
* Inferens
  - Generel information fra en stikprøve
  - Hypotesetest og konfidensintervaller
* Prædiktion
  - Forudsige udfald baseret på data
:::

:::{.notes}
Deskriptiv til at forstå data. 
Inferens - til at drage konklusioner om en hel population ud fra en stikprøve
Det er sådan noget som hypotesetest og konfidensintervaller.
Forudisge fremtidige eller ukendte observation baseret på de data vi har.
:::

## Typer af data
:::{.incremental}
* Kvantitative data
  - Kontinuærte eller diskrete, men numeriske
  - Højde, alder, vægt, blodtryk
  - Tal!
* Kvalitative (kategoriske) data
  - Ja/nej variable (gift/ugift, mand/kvinde, ryger/ikke-ryger)
  - Terningekast, socialklasse, hårfarve
:::

:::{.notes}
Kvantitative data er typisk noget vi måler. Og i princippet kan vi måle
med arbitrær præcision.
Kvalitative data er data der kun kan være i en kasse. Enten er man 
gravid. Eller også er man ikke. Man er ikke en lille smule gravid. 
Der er to typer. Nominale hvor der ikke er nogen orden. Kvinder er ikke 
bedre end mænd.
Ordinale data - og der er en orden. Det er (ofte) bedre at slå en sekser
end en treer når man kaster med terninger. 
:::

## Deskriptiv statistik til beskrivelse af data

:::: {.columns}

::: {.column width="60%"}
Hvordan kan vi beskrive datasættet til højre?

:::{.incremental}
* Minimum
* Maximum
* Gennemsnit
* Spredning
* Histogram
:::

:::

::: {.column width="40%"}
```{r echo = FALSE}
library(gt)
library(tidyverse)
c(10.2, 13.3, 10.6, 12.1,
9.3,12.0,13.4,11.9,11.2,14.6, 13.7,
12.9,10.5,12.9,13.5,12.9,12.1,11.4,15.1,11.1, 10.4,12.1,13.7,11. ,14.6,11.1,10.9,12.5,10.7,13.5, 14.9,9.4,11.8,12.7,11.2,8.8,11.3,13.0,12.9,10.9, 11.5,13.2,14.1,10.6,11.7,10.2,14.7, 1.6,13.4,13.1, 12.0,10.8,10.3,11.4,10.9,11.6,10.8,13.1,12.3,11.8, 11.0,11.7,13.6,11.9,10.4,12.5,13.3,9.7,11.0,12.2) |> 
  matrix(ncol = 7, byrow =FALSE) |>  data.frame() |> 
  gt() |> 
  tab_options(column_labels.hidden = TRUE) |> 
  tab_footnote("Haemoglobin levels in g/100 ml for 70 women")
 
```
:::

::::

## Deskriptiv statistik til beskrivelse af data








## webR i browseren
```{webr}
#| autorun: true
#| min-lines: 8
summary(cars)
plot(cars)
```

## Read-only eksempel
```{webr}
#| edit: false
mean(rnorm(100))
```
